#!/bin/bash

http PUT \
    https://api.github.com/repos/universetrainingday/Blasting-off-with-the-GitHub-API/branches/protected-branch/protection \
    Accept:application/vnd.github.loki-preview+json \
    < protected.json
