#!/bin/bash

pause() {
    if [ -z "$1" ]
    then
        echo ""
        echo ""
        echo "Press enter to continue..."
    fi
    read
}

echo_eval() {
    clear
    echo $@
    pause -
    eval $@
}

# No penalty for hitting /rate_limit
echo_eval curl https://api.github.com/rate_limit
pause
echo_eval "curl https://api.github.com/rate_limit | jq '.rate.remaining'"
pause
echo_eval "curl https://api.github.com/rate_limit | jq '.rate.remaining'"
pause
echo_eval "curl https://api.github.com/rate_limit | jq '.rate.remaining'"

# Penalized for hitting a resource, e.g. /zen
pause
echo_eval curl -i https://api.github.com/zen
pause
echo_eval "curl https://api.github.com/rate_limit | jq '.rate.remaining'"
